version: 2.1

commands:
 build-default:
  description: Default build and save artifacts for other steps
  steps:
   - checkout
   - run:
      name: Checkout module for $CIRCLE_JOB
      command: ./getsource.sh
   - run:
      name: Install build dependencies
      command: cd /tmp/build && ci-build deps
   - run:
      name: Build RPM
      command: cd /tmp/build && ci-build rpm
   - persist_to_workspace:
      root: /dist
      paths: ./*.rpm
 test-default:
  description: Default test and save tested artifacts
  steps:
   - checkout
   - attach_workspace:
      at: /dist
   - run:
      name: Checkout module for $CIRCLE_JOB
      command: ./getsource.sh
   - run:
      name: Installation test
      command: sudo yum install -y /dist/*.rpm
   - run:
      name: Test prepare
      command: cd /tmp/build && ci-build testprep
   - run:
      name: Test
      command: cd /tmp/build && ci-build test
   - store_artifacts:
      path: /dist
      destination: dist/
 
jobs:
  build-smartmet-library-newbase:
    docker:
     - image: fmidev/smartmet-cibase:latest
    steps:
     - build-default

workflows:
  version: 2-1
  build-test-and-archive:
    jobs:
    - build-smartmet-library-newbase
